import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getNotifications } from "@/lib/services/system";

const typeLabels: Record<string, string> = {
  "milestone-due": "Milestone",
  "task-delayed": "Delayed",
  "baseline-approval": "Approval",
  "critical-path-change": "Critical Path",
  "resource-conflict": "Resource",
  "schedule-slippage": "Schedule",
};

export default async function NotificationsPage() {
  const notifications = await getNotifications();

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="font-semibold text-2xl tracking-tight">Notifications</h1>
        <p className="text-muted-foreground text-sm">System notifications and alerts generated by the backend.</p>
      </div>
      <Card>
        <CardHeader>
          <CardTitle className="font-normal text-muted-foreground text-sm">Recent Notifications</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col gap-3">
            {notifications.map((n) => (
              <div
                key={n.id}
                className={`flex items-start gap-3 rounded-md border p-3 ${!n.isRead ? "bg-muted/30" : ""}`}
              >
                <div
                  className="mt-0.5 h-2 w-2 shrink-0 rounded-full"
                  style={{ backgroundColor: n.isRead ? "transparent" : "hsl(var(--primary))" }}
                />
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <span className="font-medium text-sm">{n.title}</span>
                    <Badge variant="outline" className="text-xs">
                      {typeLabels[n.type]}
                    </Badge>
                    <span className="text-muted-foreground text-xs">{n.projectCode}</span>
                  </div>
                  <p className="mt-0.5 text-muted-foreground text-sm">{n.message}</p>
                  <p className="mt-1 text-muted-foreground text-xs">
                    {new Date(n.createdAt).toLocaleDateString("en-ZA", {
                      month: "short",
                      day: "numeric",
                      hour: "2-digit",
                      minute: "2-digit",
                    })}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
